---
- name: Update Windows machines with specific KB numbers
  hosts: windows_uat
  gather_facts: no

  tasks:
    - name: Read KB numbers from file
      ansible.builtin.slurp:
        src: "updates.txt"
      register: kb_content

    - name: Convert KB content from base64
      ansible.builtin.set_fact:
        kb_list: "{{ (kb_content['content'] | b64decode).split() }}"

    - name: Install specific updates from KB numbers
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        whitelist: "{{ kb_list }}"
      register: update_result

    - name: Display update result
      ansible.builtin.debug:
        msg: "{{ update_result }}"
