---
- name: Check Windows Updates
  hosts: windows_servers
  gather_facts: false

  vars:
    api_token:

  tasks:
    - name: Get Windows Update Status
      ansible.builtin.win_shell: |
        $updateSession = New-Object -ComObject Microsoft.Update.Session
        $updateSearcher = $updateSession.CreateUpdateSearcher()
        $searchResult = $updateSearcher.Search("IsInstalled=0")
        $updatesNeeded = $searchResult.Updates

        if ($updatesNeeded.Count -eq 0) {
            Write-Output "No updates needed."
        } else {
            $updatesNeeded | ForEach-Object {
                Write-Output "$($_.Title) (KB$($_.KBArticleIDs))"
            }
        }
      become: yes
      become_method: runas
      register: result
      
    - name: Send notification message via Mattermost
      community.general.mattermost:
       url: http://chat.ansible-automates.co.za:8065
       api_key: "{{ api_token }}"
       attachments:
         - text: "!!!!!! ALERT !!!!!!"
           color: '#ff00dd'
           title: Updates
           fields:
            - title: System Updates
              value: "Updates available: {{ result.stdout_lines }}"
              short: true
      delegate_to: localhost
